(async function(){
  const app=document.getElementById('app'),debugPanel=document.getElementById('debug');
  const [settings,claims,scenes,room]=await Promise.all(['settings.json','claims.json','scenes.json','room.json'].map(file=>fetch(file,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`Could not load ${file}`);return r.json()})));
  const params=new URLSearchParams(location.search),debug=params.get('debug')==='true';
  let seed=params.get('seed')||sessionStorage.getItem('freeSaturdaySeed')||`${Date.now()}-${crypto.getRandomValues(new Uint32Array(1))[0]}`;
  sessionStorage.setItem('freeSaturdaySeed',seed);
  let assignment,state,animation;
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const findItem=id=>assignment.items.find(x=>x.claimId===id);
  function init(){const random=StudyCore.rng(`${seed}-living-room`);assignment=StudyCore.makeAssignment(settings,claims,scenes,seed);state={phase:'welcome',avatar:{x:room.avatar.startX,y:room.avatar.startY},target:null,route:[],finalDestination:null,pendingObject:null,objectAssignments:{},claimQueue:StudyCore.shuffle(assignment.items.filter(x=>x.oldNewStatus==='old'),random).map(x=>x.claimId),usedObjects:new Set(),allInteractions:new Set(),activeObject:null,activeOpenedAt:null,informationInteractions:0,movementDistance:0,controlMode:null,fillerIndex:0,testIndex:0,events:[],startedAt:new Date().toISOString(),completedAt:null};assignment.items.forEach(x=>Object.assign(x,{displayStartTime:null,displayEndTime:null,visibleDuration:0,participantChoice:null,objectOpened:null,objectOpenCount:0,qualifiedExposure:false,revisitCount:0,truthRating:null,recognitionResponse:null}));render()}
  function event(type,data={}){state.events.push({type,timestamp:new Date().toISOString(),...data});updateDebug()}
  function shell(content,className=''){stopGame();app.innerHTML=`<section class="card ${className}">${content}</section>`;app.focus();scrollTo({top:0,behavior:'instant'});postHeight();updateDebug()}
  function postHeight(){requestAnimationFrame(()=>window.parent.postMessage({type:'free-saturday-resize',height:document.documentElement.scrollHeight},'*'))}
  function render(){if(state.phase==='welcome')welcome();else if(state.phase==='room')renderRoom();else if(state.phase==='filler')filler();else if(state.phase==='test')test();else complete()}
  function welcome(){shell(`<div class="game-welcome"><p class="pixel-kicker">Imagine that you now have...</p><h1>${esc(room.title)}</h1><p class="lede">${esc(room.instructions)}</p><div class="control-guide"><span>Click or tap the floor to move</span><span>Select an object to approach and use it</span></div><p class="status">There are no right or wrong choices. Use the room however feels natural.</p><button class="primary" id="start">Enter the room</button></div>`,'game-welcome-card');document.getElementById('start').onclick=()=>{event('study_started');state.phase='room';render()}}
  function renderRoom(){const hotspots=room.objects.map(o=>`<button class="room-hotspot ${state.allInteractions.has(o.id)?'visited':''}" data-object="${esc(o.id)}" style="left:${o.x}%;top:${o.y}%;width:${o.w}%;height:${o.h}%" aria-label="${esc(o.prompt)}"><span>${esc(o.label)}</span></button>`).join('');shell(`<div class="game-shell"><header class="game-hud"><div><strong>Waiting for Sam</strong><span id="room-status">Explore the room</span></div><div class="time-chip">4:${String(Math.max(10,42-state.allInteractions.size*4)).padStart(2,'0')} PM</div></header><div class="room-stage" id="room-stage"><img src="assets/living-room-pixel.png" alt="A pixel-art living room with furniture and everyday objects" draggable="false"><div class="hotspot-layer">${hotspots}</div><div class="avatar" id="avatar" style="left:${state.avatar.x}%;top:${state.avatar.y}%;--avatar:${room.avatar.color}" aria-hidden="true"><i></i></div><div class="move-marker" id="move-marker" hidden aria-hidden="true"></div></div><p class="game-help">Click or tap anywhere to move. Select an object to approach and use it.</p></div><div id="modal-root"></div>`,'room-card');startGame();if(state.informationInteractions>=room.requiredInformationInteractions)showArrival()}
  function startGame(){const stage=document.getElementById('room-stage'),avatar=document.getElementById('avatar'),marker=document.getElementById('move-marker');stage.onclick=e=>{if(e.target.closest('[data-object]'))return;const rect=stage.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*100,y=(e.clientY-rect.top)/rect.height*100;state.controlMode='pointer';state.pendingObject=null;setDestination(x,y);marker.hidden=false;marker.style.left=`${state.finalDestination.x}%`;marker.style.top=`${state.finalDestination.y}%`;event('floor_destination_selected',{targetX:Math.round(state.finalDestination.x*10)/10,targetY:Math.round(state.finalDestination.y*10)/10})};app.querySelectorAll('[data-object]').forEach(b=>b.onclick=e=>{e.stopPropagation();state.controlMode='pointer';approachObject(b.dataset.object,true)});let last=performance.now();function frame(now){const dt=Math.min(40,now-last);last=now;if(state.target){const tx=state.target.x-state.avatar.x,ty=state.target.y-state.avatar.y,d=Math.hypot(tx,ty);if(d<1.2){state.avatar.x=state.target.x;state.avatar.y=state.target.y;if(state.route.length)state.target=state.route.shift();else{state.target=null;marker.hidden=true;if(state.pendingObject){const id=state.pendingObject;state.pendingObject=null;openObject(id)}}}else{const step=Math.min(d,.025*dt);moveAvatar(tx/d*step,ty/d*step)}}avatar.style.left=`${state.avatar.x}%`;avatar.style.top=`${state.avatar.y}%`;animation=requestAnimationFrame(frame)}animation=requestAnimationFrame(frame)}
  function stopGame(){if(animation)cancelAnimationFrame(animation);animation=null}
  function moveAvatar(dx,dy){const ox=state.avatar.x,oy=state.avatar.y;state.avatar.x=Math.max(7,Math.min(93,state.avatar.x+dx));state.avatar.y=Math.max(38,Math.min(91,state.avatar.y+dy));state.movementDistance+=Math.hypot(state.avatar.x-ox,state.avatar.y-oy)}
  function obstacleRects(){return (room.movementObstacles||[]).map(o=>({id:o.id,left:o.x-o.margin,right:o.x+o.w+o.margin,top:o.y-o.margin,bottom:o.y+o.h+o.margin}))}
  function isInside(p,r){return p.x>r.left&&p.x<r.right&&p.y>r.top&&p.y<r.bottom}
  function normalizeDestination(x,y){let p={x:Math.max(7,Math.min(93,x)),y:Math.max(38,Math.min(91,y))};for(const r of obstacleRects())if(isInside(p,r)){const options=[{x:r.left-.5,y:p.y},{x:r.right+.5,y:p.y},{x:p.x,y:r.top-.5},{x:p.x,y:r.bottom+.5}];p=options.reduce((best,q)=>Math.hypot(q.x-p.x,q.y-p.y)<Math.hypot(best.x-p.x,best.y-p.y)?q:best)}return p}
  function segmentBlocked(a,b){return obstacleRects().some(r=>{for(let i=1;i<50;i++){const t=i/50,p={x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t};if(isInside(p,r))return true}return false})}
  function planRoute(start,end){const nodes=[start,end];obstacleRects().forEach(r=>nodes.push({x:r.left-.5,y:r.top-.5},{x:r.right+.5,y:r.top-.5},{x:r.right+.5,y:r.bottom+.5},{x:r.left-.5,y:r.bottom+.5}));const dist=nodes.map(()=>Infinity),prev=nodes.map(()=>-1),seen=nodes.map(()=>false);dist[0]=0;for(let step=0;step<nodes.length;step++){let u=-1;for(let i=0;i<nodes.length;i++)if(!seen[i]&&(u<0||dist[i]<dist[u]))u=i;if(u<0||!isFinite(dist[u]))break;seen[u]=true;for(let v=0;v<nodes.length;v++)if(!seen[v]&&!segmentBlocked(nodes[u],nodes[v])){const alt=dist[u]+Math.hypot(nodes[v].x-nodes[u].x,nodes[v].y-nodes[u].y);if(alt<dist[v]){dist[v]=alt;prev[v]=u}}}if(!isFinite(dist[1]))return[end];const path=[];for(let at=1;at>0;at=prev[at])path.unshift(nodes[at]);return path}
  function setDestination(x,y){const end=normalizeDestination(x,y),path=planRoute({...state.avatar},end);state.finalDestination=end;state.route=path;state.target=state.route.shift()||null}
  function approachObject(id,openWhenReached){const o=room.objects.find(x=>x.id===id);setDestination(o.targetX,o.targetY);state.pendingObject=openWhenReached?id:null;event('object_approach_started',{objectOpened:id,avatarX:state.avatar.x,avatarY:state.avatar.y,controlMode:state.controlMode,routeWaypoints:state.route.length+(state.target?1:0)})}
  function openObject(id){const o=room.objects.find(x=>x.id===id);if(!o)return;state.allInteractions.add(id);state.activeObject=id;state.activeOpenedAt=Date.now();let item=null;if(o.kind==='information'){if(!state.objectAssignments[id]&&state.claimQueue.length){state.objectAssignments[id]=state.claimQueue.shift();state.usedObjects.add(id);state.informationInteractions++}if(state.objectAssignments[id]){item=findItem(state.objectAssignments[id]);item.objectOpened=id;item.participantChoice=id;item.presentationFormat=o.format;item.objectOpenCount++;item.revisitCount=Math.max(0,item.objectOpenCount-1);if(!item.displayStartTime)item.displayStartTime=new Date().toISOString();event('object_opened',{objectOpened:id,claimId:item.claimId,baseClaimId:item.baseClaimId,relevanceCondition:item.relevanceCondition,group:item.group,revisit:item.revisitCount>0,exposureOrder:state.informationInteractions})}}else event('filler_object_opened',{objectOpened:id});showObjectModal(o,item)}
  function showObjectModal(o,item){const root=document.getElementById('modal-root');const content=item?`<div class="standardized-exposure"><p class="claim-label">${esc(room.claimPresentation.label)}</p><p class="room-claim">${esc(item.text)}</p></div>`:`<p>${esc(o.response||'You look for a moment, then set it back where it was.')}</p>`;root.innerHTML=`<div class="object-modal-backdrop"><section class="object-modal format-${esc((o.format||'filler').replaceAll(' ','-'))}" role="dialog" aria-modal="true" aria-labelledby="object-title"><header><span>${esc(o.label)}</span><button id="close-modal" aria-label="Close ${esc(o.label)}">×</button></header>${item?`<p class="source-label">${esc(o.source)}</p><h2 id="object-title">${esc(o.headline)}</h2>`:`<h2 id="object-title">${esc(o.prompt)}</h2>`}<div class="object-copy">${content}</div><button class="primary" id="done-object">${o.kind==='information'?'Put it down':'Done'}</button></section></div>`;document.getElementById('close-modal').onclick=closeObject;document.getElementById('done-object').onclick=closeObject;document.getElementById('done-object').focus();postHeight()}
  function closeObject(){const id=state.activeObject,o=room.objects.find(x=>x.id===id),duration=Date.now()-state.activeOpenedAt,itemId=state.objectAssignments[id],item=itemId?findItem(itemId):null;if(item){item.visibleDuration+=duration;item.displayEndTime=new Date().toISOString();item.qualifiedExposure=item.visibleDuration>=1500;event('object_closed',{objectOpened:id,claimId:item.claimId,visibleDuration:item.visibleDuration,qualifiedExposure:item.qualifiedExposure,revisitCount:item.revisitCount})}else event('filler_object_closed',{objectOpened:id,interactionDuration:duration});state.activeObject=null;state.activeOpenedAt=null;document.getElementById('modal-root').innerHTML='';document.querySelector(`[data-object="${CSS.escape(id)}"]`)?.classList.add('visited');if(state.informationInteractions>=room.requiredInformationInteractions)showArrival()}
  function showArrival(){if(document.getElementById('arrival-card'))return;const root=document.getElementById('modal-root');root.innerHTML=`<div class="arrival-toast" id="arrival-card"><span>New message</span><strong>Sam: I’m outside whenever you’re ready.</strong><div><button class="secondary" id="stay-room">Stay a little longer</button><button class="primary" id="leave-room">Head outside</button></div></div>`;document.getElementById('stay-room').onclick=()=>root.innerHTML='';document.getElementById('leave-room').onclick=finishRoom}
  function finishRoom(){event('room_completed',{informationInteractions:state.informationInteractions,totalObjectsInteracted:state.allInteractions.size,movementDistance:Math.round(state.movementDistance),controlMode:state.controlMode});state.phase='filler';render()}
  function filler(){const f=settings.filler;if(state.fillerIndex===0&&!state.events.some(x=>x.type==='filler_started'))event('filler_started');const item=f.items[state.fillerIndex];shell(`<p class="eyebrow">A quick change of pace</p><h2>${esc(f.title)}</h2><p>${esc(f.instructions)}</p><h3>${esc(item.prompt)}</h3><div class="choices">${item.options.map(o=>`<button class="choice" data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div>`);app.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{event('filler_response',{itemOrder:state.fillerIndex+1,prompt:item.prompt,response:b.dataset.answer});state.fillerIndex++;if(state.fillerIndex>=f.items.length)state.phase='test';render()})}
  function test(){const item=findItem(assignment.testOrder[state.testIndex]);item.testDisplayStartTime=new Date().toISOString();if(item.oldNewStatus==='new')item.displayStartTime=item.testDisplayStartTime;shell(`<p class="eyebrow">Statement ${state.testIndex+1} of ${assignment.testOrder.length}</p><h2>How true is this statement?</h2><blockquote class="test-claim"><p>${esc(item.text)}</p></blockquote><form id="rating-form"><div class="scale-labels"><span>Definitely false</span><span>Definitely true</span></div><div class="rating">${Array.from({length:7},(_,i)=>i+1).map(n=>`<label><input required type="radio" name="rating" value="${n}">${n}</label>`).join('')}</div>${settings.recognitionEnabled?`<fieldset class="recognition"><legend>Do you remember encountering this statement in the room? <span class="status">(optional)</span></legend><label><input type="radio" name="recognition" value="yes"> Yes</label><label><input type="radio" name="recognition" value="no"> No</label><label><input type="radio" name="recognition" value="unsure"> Not sure</label></fieldset>`:''}<button class="primary" type="submit">Save and continue</button></form>`);document.getElementById('rating-form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.currentTarget),end=new Date();item.truthRating=Number(data.get('rating'));item.recognitionResponse=data.get('recognition')||null;item.testDisplayEndTime=end.toISOString();item.testVisibleDuration=end-new Date(item.testDisplayStartTime);if(item.oldNewStatus==='new'){item.displayEndTime=item.testDisplayEndTime;item.visibleDuration=item.testVisibleDuration}event('truth_rating',{claimId:item.claimId,baseClaimId:item.baseClaimId,relevanceCondition:item.relevanceCondition,oldNewStatus:item.oldNewStatus,group:item.group,qualifiedExposure:item.qualifiedExposure,itemOrder:item.itemOrder,truthRating:item.truthRating,recognitionResponse:item.recognitionResponse});state.testIndex++;if(state.testIndex>=assignment.testOrder.length){state.phase='complete';state.completedAt=new Date().toISOString()}render()}}
  function result(){return {study:settings.studyTitle,paradigm:'pixel-living-room',participantSeed:assignment.seed,irrelevantIdentities:assignment.irrelevantIdentities,startedAt:state.startedAt,completedAt:state.completedAt,claims:assignment.items.map(x=>({...x})),objectAssignments:{...state.objectAssignments},roomSummary:{informationInteractions:state.informationInteractions,objectsInteracted:[...state.allInteractions],movementDistance:Math.round(state.movementDistance),controlMode:state.controlMode},eventLog:state.events,fillerResponses:state.events.filter(x=>x.type==='filler_response')}}
  function complete(){if(!state.events.some(x=>x.type==='study_completed'))event('study_completed');window.parent.postMessage({type:'free-saturday-complete',result:result()},'*');shell(`<p class="eyebrow">Complete</p><h2>${esc(settings.completionMessage)}</h2><p>You may now close this page.</p>${window.parent===window?'<button class="secondary" id="download">Download my session data</button>':''}`);const d=document.getElementById('download');if(d)d.onclick=exportData}
  function exportData(){const blob=new Blob([JSON.stringify(result(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`living-room-${assignment.seed}.json`;a.click();URL.revokeObjectURL(a.href)}
  function skip(){if(state.phase==='welcome'){state.phase='room'}else if(state.phase==='room'){const unused=room.objects.filter(o=>o.kind==='information'&&!state.objectAssignments[o.id]).slice(0,room.requiredInformationInteractions-state.informationInteractions);unused.forEach(o=>{state.objectAssignments[o.id]=state.claimQueue.shift();state.informationInteractions++;state.allInteractions.add(o.id)});finishRoom();return}else if(state.phase==='filler'){state.phase='test'}else if(state.phase==='test'){state.testIndex++;if(state.testIndex>=assignment.testOrder.length)state.phase='complete'}render()}
  function updateDebug(){if(!debug)return;debugPanel.hidden=false;debugPanel.innerHTML=`<strong>DEBUG · seed ${esc(seed)}</strong><div><button id="dbg-skip">Advance</button><button id="dbg-same">Restart same seed</button><button id="dbg-new">New seed</button><button id="dbg-export">Export JSON</button></div><p>Room exposures: ${state.informationInteractions}/${room.requiredInformationInteractions}</p><details><summary>Assignment</summary><pre>${esc(JSON.stringify(assignment,null,2))}</pre></details><details open><summary>Event log (${state.events.length})</summary><pre>${esc(JSON.stringify(state.events.slice(-15),null,2))}</pre></details>`;document.getElementById('dbg-skip').onclick=skip;document.getElementById('dbg-same').onclick=init;document.getElementById('dbg-new').onclick=()=>{seed=`${Date.now()}-${crypto.getRandomValues(new Uint32Array(1))[0]}`;sessionStorage.setItem('freeSaturdaySeed',seed);init()};document.getElementById('dbg-export').onclick=exportData}
  if(debug)document.body.insertAdjacentHTML('beforeend','<span class="debug-badge">Debug mode</span>');init();
})().catch(error=>{document.getElementById('app').innerHTML=`<section class="card"><h1>Study unavailable</h1><p>${error.message}</p></section>`});
