const assert=require('assert');const fs=require('fs');const Core=require('./study-core.js');
const appSource=fs.readFileSync('app.js','utf8');
const visitedIndicatorCss=fs.readFileSync('no-visited-indicators.css','utf8');
const settings=JSON.parse(fs.readFileSync('settings.json'));const claims=JSON.parse(fs.readFileSync('claims.json'));const scenes=JSON.parse(fs.readFileSync('scenes.json'));const feed=JSON.parse(fs.readFileSync('feed.json'));const room=JSON.parse(fs.readFileSync('room.json'));
function assignment(seed='test-seed'){return Core.makeAssignment(settings,claims,scenes,seed)}
const a=assignment(),v=Core.validateAssignment(a,settings);
assert.equal(v.counts.relevantOld,settings.exposedPerCondition,'configured relevant exposed');assert.equal(v.counts.irrelevantOld,settings.exposedPerCondition,'configured irrelevant exposed');
assert.equal(v.counts.relevantNew,settings.newPerCondition,'configured relevant new');assert.equal(v.counts.irrelevantNew,settings.newPerCondition,'configured irrelevant new');
assert(v.uniqueBaseClaims,'no duplicated base-claim families');assert(v.noBothVariants,'never both identity variants');
assert.deepStrictEqual(assignment('repeatable'),assignment('repeatable'),'reproducible from seed');
assert.notDeepStrictEqual(assignment('repeatable'),assignment('different'),'different seeds differ');
assert.equal(scenes.scenes.length,8,'eight scenes');scenes.scenes.forEach(s=>{assert(s.choices.length>=2&&s.choices.length<=3);assert(s.choices.every(c=>c.response&&c.object&&c.format&&c.beforeClaim&&c.afterClaim),'each branch has natural content and a convergent response')});
const required=['claimId','baseClaimId','relevanceCondition','oldNewStatus','scene','presentationFormat','displayStartTime','displayEndTime','visibleDuration','participantChoice','truthRating','recognitionResponse','itemOrder'];
a.items.forEach(item=>required.forEach(field=>assert(Object.prototype.hasOwnProperty.call(item,field),`required field ${field}`)));
assert(a.items.filter(x=>x.oldNewStatus==='old').every(x=>x.scene&&x.presentationFormat),'all exposures assigned');
const branchFormats=new Set(scenes.scenes.flatMap(s=>s.choices.map(c=>c.format)));assert(branchFormats.size>=5,'branches use varied naturalistic formats');
const phoneApps=new Set(['Messages','News','Recipes','Maps','Transit','Local Guide','Tickets','Nearby','Cinema','Reader','Reminders','Email','Podcasts','Watch']);
scenes.scenes.flatMap(s=>s.choices).forEach(c=>assert(phoneApps.has(c.object),`${c.object} is a phone-native app`));
assert.equal(feed.fillerCards.length,16,'sixteen filler cards conceal eight claim cards');assert.equal(feed.claimContexts.length,8,'eight matched editorial contexts');assert(claims.claims.every(c=>feed.categories.includes(c.category)),'every claim has an editable feed category');assert(feed.minimumSaves>=3,'feed requires meaningful curation');
assert.equal(room.objects.filter(o=>o.kind==='information').length,10,'ten deliberate information objects');assert(room.objects.filter(o=>o.kind==='filler').length>=6,'room includes genuine filler interactions');assert.equal(room.requiredInformationInteractions,settings.exposedPerCondition*2,'room delivers a balanced exposure queue');
assert(room.claimPresentation&&room.claimPresentation.label,'standardized claim label is configurable');
room.objects.filter(o=>o.kind==='information').forEach(o=>{assert(!('before' in o)&&!('after' in o)&&!('detail' in o),`${o.id} has no item-specific surrounding claim context`)});
assert(appSource.includes('class="standardized-exposure"'),'exposures use a shared presentation component');assert(!appSource.includes('o.before')&&!appSource.includes('o.after')&&!appSource.includes('o.detail'),'renderer cannot add object-specific claim context');
assert.equal(new Set(a.items.filter(x=>x.oldNewStatus==='old'&&x.relevanceCondition==='irrelevant').map(x=>x.group)).size,settings.exposedPerCondition,'irrelevant exposures use distinct identities');
assert(appSource.includes('floor_destination_selected'),'empty-floor click-to-move is implemented');assert(!appSource.includes('WASD'),'participant instructions do not require keyboard movement');
assert(visitedIndicatorCss.includes('content: none'),'visited objects have no on-screen completion marker');
assert(room.movementObstacles.some(o=>o.id==='coffee-table'),'coffee table is configured as a movement obstacle');
assert(appSource.includes('planRoute')&&appSource.includes('segmentBlocked'),'avatar movement routes around configured obstacles');
room.objects.forEach(o=>room.movementObstacles.forEach(r=>{const m=r.margin;assert(!(o.targetX>r.x-m&&o.targetX<r.x+r.w+m&&o.targetY>r.y-m&&o.targetY<r.y+r.h+m),`${o.id} interaction target is reachable outside ${r.id}`)}));
console.log('✓ all assignment, convergence, reproducibility, and data-schema tests passed');
